// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp5F8_qIxIlstCThCccJZFk6uoZLMx-ww',
    appId: '1:672117213245:web:0dc5cc5b92a29bb27e4254',
    messagingSenderId: '672117213245',
    projectId: 'my-newsapp-dailycapsule',
    authDomain: 'my-newsapp-dailycapsule.firebaseapp.com',
    storageBucket: 'my-newsapp-dailycapsule.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEC71Dzw6SEsafdUcsePq7XMANaYj3vWU',
    appId: '1:672117213245:android:d8e758bc0077918d7e4254',
    messagingSenderId: '672117213245',
    projectId: 'my-newsapp-dailycapsule',
    storageBucket: 'my-newsapp-dailycapsule.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC75g1OvGhCINNF4hiPpHEXneqT_o_KyYE',
    appId: '1:672117213245:ios:939d73a6884b6dd07e4254',
    messagingSenderId: '672117213245',
    projectId: 'my-newsapp-dailycapsule',
    storageBucket: 'my-newsapp-dailycapsule.appspot.com',
    iosBundleId: 'com.dailyreport.dailyReport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC75g1OvGhCINNF4hiPpHEXneqT_o_KyYE',
    appId: '1:672117213245:ios:cd9d4c171a8fa6a27e4254',
    messagingSenderId: '672117213245',
    projectId: 'my-newsapp-dailycapsule',
    storageBucket: 'my-newsapp-dailycapsule.appspot.com',
    iosBundleId: 'com.daily.capsule',
  );
}
